support to run example/test.py and integrate optimized gemm/attention operator
alibaba/rtp-llm pull request #113
Opened 2024-09-12 03:12 UTC by TianyuLi0

Support to run example/test.py on Arm 
Integrate optimized gemm kernel from Xujie
Integrate optimized attention operator from Ruifeng
Integrate sampleGreedy from Haijiang
Fix rebase/integration issues

Note: some workarounds applied to pass build,
Turn off warning as error,
Workspace/bazel build change
requirements txt chagne,
May need to revert before merge.

To run the example:
bazel test //example:test  --config=arm --test_output=all

2024-09-12 03:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/rtp-llm?pullRequest=113) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/rtp-llm?pullRequest=113) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: TianyuLi0<br/>:white_check_mark: Reyfone<br/>:x: fishcrap<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/rtp-llm?pullRequest=113) it.</sub>

2024-09-19 01:57 UTC, netaddi requested changes

2024-09-19 01:57 UTC, netaddi commented on .bazelrc
you can not comment this for all build configs. specify this only for arm.

2024-09-19 03:17 UTC, TianyuLi0 commented on .bazelrc
OK. Removed global copt and moved to arm specific flags.

2024-09-19 03:29 UTC, merged